name: Update App JSON

on:
  push:
    branches:
      - staging

jobs:
  update_app_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run script
      run: |
        python script.py app.json ZARATE 111111


    - name: Commit and push changes to production branch
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add app.json
        git commit -m "Update app.json"
        git push origin HEAD:production
