name: Update App JSON

on:
  push:
    branches:
      - staging

jobs:
  update_app_json:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run script
      run: |
        python script.py app.json ZARATE 111111


    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: production
