name: Update App JSON

on:
  push:
    branches:
      - staging
      - production

jobs:
  update_app_json:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        branch:
          - staging
            script_args: "app.json ZARATE 111111"
            commit_branch: "production"
          - production
            script_args: "app.json 111111 ZARATE"
            commit_branch: "staging"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run script
      run: |
        python script.py ${{ matrix.script_args }}

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: ${{ matrix.commit_branch }}
